### ISSUE TITLE
Allow variable node version

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/github-action-for-generator#132]
#### Reason/Context
Had a use case where a dependency for a template needed >= v14 however this action runs with v12, making them incompatible.

#### Description
Would be great if it offered a way to use different node versions for the generation.

**Comment by derberg** [comment]
@jonaslagoni I'm not sure how this could be done really 🤷🏼 In docs there is nothing about it https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions. I can fix specific version, not like >=.

Maybe just change to 14? 🤔 in theory all should be good, right? 🤔

**Comment by jonaslagoni** [comment]
> I can fix specific version, not like >=.

Is it not possible to supply the version through environment variables? 

> Maybe just change to 14? 🤔 in theory all should be good, right? 🤔

Maybe, not entirely sure on the changes in node, and whether a template would in any case need a lower version of node 🤔

**Comment by derberg** [comment]
I'm not aware of such tricks 😄 

maybe it would work, that a step before running action you do:
```
        name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
```
but I don't know if that would work, you would have to test it

**Comment by jonaslagoni** [comment]
> but I don't know if that would work, you would have to test it

Won't work, 'cause that was the first step I tried, before realizing this GitHub action had its own version 😆 

I just did not use this GitHub action but `actions/setup-node@v1` and manually installed the generator globally and then generated what ever I needed 🙂

**Comment by derberg** [comment]
yeah, and it actually must always be `node12` -> https://json.schemastore.org/github-action.json

so workaround is you either do it your way or you add some post-install script to your template that transpile with babel your template into node 12

**Comment by jonaslagoni** [comment]
> yeah, and it actually must always be `node12` -> https://json.schemastore.org/github-action.json

@derberg that is a bit of a weird requirement, is it not? 🧐

**Comment by derberg** [comment]
it is, probably related to runtime used to call these actions 🤷🏼 12 is in maintenance mode until may next year, so this will most probably change in few months

**Comment by jonaslagoni** [comment]
Right, I guess this is unresolvable then 😄 Closing as there is a workaround - https://github.com/asyncapi/github-action-for-generator/issues/132#issuecomment-913512789
