### ISSUE TITLE
Refactor and rename this GH Action to be fully AsyncAPI CLI based

### ISSUE THREAD

**Issue by derberg** [asyncapi/github-action-for-generator#281]
When I worked on this action some time ago, my main motivation was:
- provide GH action for generator
- do it by using Generator as library because:
    - we have automated releases (for node projects) implemented in AsyncAPI organization, so I knew that whenever new Generator is released, it will trigger release of this action to also support latest release
    - because wanted to use Generator as library in production and figure how that works 🤷🏼 

Now times are different 😄 

I think it would be better:
- release 3.0 version of the action
- rename action from `Generator for AsyncAPI documents` to `Generator, validator, converter and others - all in one for your AsyncAPI docs`
- rename repository from `github-action-for-generator` to `github-action-for-asyncapi-cli`
- throw away all the Nodejs code and modify docker file to simply expose the AsyncAPI CLI interface - example GH Action that does it https://github.com/gaurav-nelson/github-action-markdown-link-check

Or:
Or we just archive this repo and create action directly in AsyncAPI CLI - example how a friend does it (CLI and GH action for it in one repo) https://github.com/mszostok/codeowners-validator. I think it makes sense, especially that in ourcase GH Action would anyway always reflect the CLI version. Current action we would just archive, set as deprecated and link to the new one.

Thoughts?

**Comment by christianrowlands** [comment]
Great summary of the options.

Creating the action directly in the CLI repo does sound the best, as long as the action does not get lost in all the other CLI documentation. Google searching made it easy to find this repo. Hopefully that would still work if you migrated it.

**Comment by derberg** [comment]
still needed

**Comment by derberg** [comment]
Let's do it in 2 steps:

- first do all refactor/rename here
- discuss if we can/should move to CLI

**Comment by derberg** [comment]
current scope:
- release 3.0 version of the action
- rename action from `Generator for AsyncAPI documents` to `Generator, validator, converter and others - all in one for your AsyncAPI docs`
- rename repository from `github-action-for-generator` to `github-action-for-asyncapi-cli`
- throw away all the Nodejs code and modify docker file to simply expose the AsyncAPI CLI interface - example GH Action that does it https://github.com/gaurav-nelson/github-action-markdown-link-check
- we still need a lot of custom action parameters, like `template` or others
- good docs explanation with examples of different configurations, like validating in one step and generating in another one
- tests that make sure action works (might be that some JS code will stay to facilitate testing)

**Comment by Shurtu-gal** [comment]
Hey @derberg, can I work on this?

**Comment by mhmohona** [comment]
I want to work on this issue.

**Comment by sambhavgupta0705** [comment]
@derberg I would like to work on this one as I have experience of working with GH so I think I will be able to resolve this one

**Comment by aeworxet** [comment]
Bounty Issue's End Of Life (EOL): [2024-02-29 23:59:59 UTC-12:00](https://time.lol/#2024-02-29T23:59:59-12:00)

**Comment by codingmickey** [comment]
Hi I would love to work on this! I've had worked with gh actions in the past extensively :)

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2023-11-13                 |[2023-11-20](https://time.lol/#2023-11-20T00:00:00+12:00)              |**[2024-01-12](https://time.lol/#2024-01-12T23:59:59-12:00)**        |[2023-12-08](https://time.lol/#2023-12-08T23:59:59-12:00)         |[2023-12-29](https://time.lol/#2023-12-29T23:59:59-12:00)         |**[2024-01-12](https://time.lol/#2024-01-12T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by Shurtu-gal** [comment]
> we still need a lot of custom action parameters, like `template` or others.

@derberg as we would be exposing the cli interface directly, should I take parameters as a json and pass them unto cli in docker or something else. As the CLI has various topics and subtopics inside of it further down.

**Comment by aeworxet** [comment]
Due to unpredicted circumstances that could not be foreseen and are beyond the control of the AsyncAPI Maintainer (@derberg), the Bounty Issue's Timeline is frozen for an indefinite amount of time.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2023-11-13                 |[2023-11-20](https://time.lol/#2023-11-20T00:00:00+12:00)              |**[2024-02-09](https://time.lol/#2024-02-09T23:59:59-12:00)**        |[2024-01-05](https://time.lol/#2024-01-05T23:59:59-12:00)         |[2024-01-26](https://time.lol/#2024-01-26T23:59:59-12:00)         |**[2024-02-09](https://time.lol/#2024-02-09T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by aeworxet** [comment]
AsyncAPI Maintainer (@derberg) was absent online in [Slack](https://asyncapi.slack.com) for one period of three working days in a row, so all target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2023-11-13                 |[2023-11-20](https://time.lol/#2023-11-20T00:00:00+12:00)              |**[2024-02-23](https://time.lol/#2024-02-23T23:59:59-12:00)**        |[2024-01-19](https://time.lol/#2024-01-19T23:59:59-12:00)         |[2024-02-09](https://time.lol/#2024-02-09T23:59:59-12:00)         |**[2024-02-23](https://time.lol/#2024-02-23T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by derberg** [comment]
@aeworxet bounty completed like a pro 💪🏼 you can go ahead and instruct @Shurtu-gal how to get the payment

**Comment by aeworxet** [comment]
### Bounty Issue Completed 🎉

Please go to the [AsyncAPI's OpenCollective page](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the subject `Bounty github-action-for-generator#281`, tag `bounty`.
