### ISSUE TITLE
Github action creating pdf fails because of puppeteer

### ISSUE THREAD

**Issue by oliverunger** [asyncapi/github-action-for-generator#329]
#### Describe the bug
Generator fails to create asyncapi pdf

#### How to Reproduce
Using the following step:
      - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.1.12
        with:
          template: '@asyncapi/html-template@0.28.0'
          filepath: api/src/main/resources/docs/api/my_asyncapi.yml
          parameters: pdf=true
          output: wiki/diagrams

Github Actions Log:
PDF is generating...
Error: Failed to launch the browser process! spawn /node_modules/@asyncapi/generator/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/node_modules/@asyncapi/generator/node_modules/puppeteer/src/node/BrowserRunner.ts:304:[9](https://github.com/XXX/XYZ/actions/runs/6024020451/job/16341900878#step:7:10))
    at ChildProcess.<anonymous> (/node_modules/@asyncapi/generator/node_modules/puppeteer/src/node/BrowserRunner.ts:296:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:[12](https://github.com/XXX/XYZ/actions/runs/6024020451/job/16341900878#step:7:13))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:[16](https://github.com/XXX/XYZ/actions/runs/6024020451/job/16341900878#step:7:17))
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

#### Expected behavior
Should create a beautiful pdf of my asyncapi.

**Comment by derberg** [comment]
might be that we need to improve https://github.com/asyncapi/github-action-for-generator/blob/master/Dockerfile and follow what we did in https://github.com/asyncapi/generator/blob/master/Dockerfile (so have puppeteer dedicated config).

@oliverunger can you open a PR?

**Comment by oliverunger** [comment]
Hello @derberg 
Thank you for your quick response!
Using 
`asyncapi generate fromTemplate my_asyncapi.yml @asyncapi/html-template@0.28.0 -p pdf=true singleFile=true`
worked well and generated a .pdf and a .html for me with the following logs:
```
PDF is generating...
PDF generated!
Generation in progress. Keep calm and wait a bit... done
Check out your shiny new generated files at C:\git-repos\myproject.
```

**Comment by oliverunger** [comment]
This worked for me in my github workflow but its suboptimal:
```
      - name: Install Asyncapi generator
        run: npm install -g @asyncapi/generator

      - name: Generating PDF from my AsyncAPI document
        run: ag my_asyncapi.yml @asyncapi/html-template@0.28.0 -p pdf=true singleFile=true -o wiki/diagrams
```

Very bad: The generated pdf is full expanded.
Good: Links are clickable

**Comment by derberg** [comment]
The fact that PDF is fully expanded was [done intentionally](https://github.com/asyncapi/html-template/blob/master/hooks/99_generatePdf.js#L28-L32). I'm not a PDF expert and [assumption was](https://github.com/asyncapi/html-template/pull/82#discussion_r500829077) it must be expanded, otherwise generated PDF will be "broken" as we were not sure expand/collapse will work + `cntrl + f` will not work

**Comment by derberg** [comment]
looks like fixed.

if there is a strong and clear vision how to improve PDF, please open an issue in https://github.com/asyncapi/html-template
